# Generated by Django 2.1.2 on 2020-12-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.IntegerField()),
                ('total_order', models.IntegerField()),
                ('total_customer', models.IntegerField()),
                ('top_product', models.TextField()),
                ('top_customer', models.TextField()),
                ('top_seller', models.TextField()),
                ('trend_region', models.TextField()),
            ],
        ),
    ]
