# Generated by Django 2.1.2 on 2020-12-23 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='top_customer',
            new_name='top_customers',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='top_product',
            new_name='top_products',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='top_seller',
            new_name='trend_seller',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
