# Generated by Django 2.1.2 on 2020-12-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201223_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
